FROM i386/ubuntu:latest
Maintainer Suganya Athimuthu (suganya@wobe-systems.com)
# Update aptitude with new repo
RUN apt-get update

#Install software
RUN apt-get install -y gcc cmake g++ git splint flawfinder